[package]
name = "hasten"
version = "0.1.0"
authors = ["Giovanni Petrantoni <giovanni@fragcolor.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
